2023/06/15 07:09:00 [error] [exception.ParseError] ParseError: Unclosed '(' does not match '}' in C:\xampp\htdocs\yii\web\helpers\CJSON.php:553
Stack trace:
#0 C:\xampp\htdocs\yii\validators\CRequiredValidator.php(113): YiiBase::autoload('CJSON')
#1 C:\xampp\htdocs\yii\web\widgets\CActiveForm.php(510): CRequiredValidator->clientValidateAttribute(Object(ContactForm), 'name')
#2 C:\xampp\htdocs\pruebaTecnica\protected\views\site\contact.php(43): CActiveForm->error(Object(ContactForm), 'name')
#3 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('contact', Array, true)
#7 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(72): CController->render('contact', Array)
#8 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionContact()
#9 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('contact')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/contact')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=site/contact
HTTP_REFERER=http://localhost/pruebaTecnica/
---
2023/06/15 07:22:47 [error] [php] mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() (C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php:67)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\xampp\htdocs\yii\web\CController.php(286): SiteController->runAction()
#2 C:\xampp\htdocs\yii\web\CController.php(265): SiteController->runActionWithFilters()
#3 C:\xampp\htdocs\yii\web\CWebApplication.php(282): SiteController->run()
#4 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#5 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#6 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php?r=site/contact
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php (67)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/15 07:43:16 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "usuarios". in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=usuarios
---
2023/06/15 08:12:53 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "gii". in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=gii
---
2023/06/15 08:17:08 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "gii". in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=gii
---
2023/06/15 08:17:27 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "gii". in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=gii
---
2023/06/15 08:17:45 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "gii". in C:\xampp\htdocs\yii\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(270): CController->missingAction('gii')
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('gii')
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/gii')
#3 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=site/gii
---
2023/06/15 08:17:51 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "gii". in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=gii
---
2023/06/15 08:17:54 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "yii". in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('yii')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=yii
---
2023/06/15 17:54:13 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''. The SQL statement executed was: SHOW FULL COLUMNS FROM ``.
2023/06/15 17:54:13 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''. The SQL statement executed was: SHOW FULL COLUMNS FROM ``.
2023/06/15 20:22:55 [error] [php] Only the first byte will be assigned to the string offset (C:\xampp\htdocs\yii\gii\generators\model\ModelCode.php:407)
Stack trace:
#0 C:\xampp\htdocs\yii\gii\CCodeGenerator.php(162): ModelCode->prepare()
#1 C:\xampp\htdocs\yii\gii\CCodeGenerator.php(63): ModelGenerator->prepare()
#2 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ModelGenerator->actionIndex()
#3 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\yii\web\CController.php(286): ModelGenerator->runAction()
#5 C:\xampp\htdocs\yii\web\CController.php(265): ModelGenerator->runActionWithFilters()
#6 C:\xampp\htdocs\yii\web\CWebApplication.php(282): ModelGenerator->run()
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php?r=gii/model/index
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/15 21:10:18 [error] [exception.CException] CException: Property "CWebUser.identityClass" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CWebUser.php(160): CComponent->__set('identityClass', 'app\\models\\User')
#1 C:\xampp\htdocs\yii\YiiBase.php(220): CWebUser->__set('identityClass', 'app\\models\\User')
#2 C:\xampp\htdocs\yii\base\CModule.php(393): YiiBase::createComponent(Array)
#3 C:\xampp\htdocs\yii\web\CWebApplication.php(209): CModule->getComponent('user')
#4 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(132): CWebApplication->getUser()
#5 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/create')
#13 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=usuarios/create
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=usuarios
---
2023/06/15 21:10:24 [error] [exception.CException] CException: Property "CWebUser.identityClass" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CWebUser.php(160): CComponent->__set('identityClass', 'app\\models\\User')
#1 C:\xampp\htdocs\yii\YiiBase.php(220): CWebUser->__set('identityClass', 'app\\models\\User')
#2 C:\xampp\htdocs\yii\base\CModule.php(393): YiiBase::createComponent(Array)
#3 C:\xampp\htdocs\yii\web\CWebApplication.php(209): CModule->getComponent('user')
#4 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(132): CWebApplication->getUser()
#5 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios')
#13 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=usuarios
---
2023/06/15 21:10:26 [error] [exception.CException] CException: Property "CWebUser.identityClass" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CWebUser.php(160): CComponent->__set('identityClass', 'app\\models\\User')
#1 C:\xampp\htdocs\yii\YiiBase.php(220): CWebUser->__set('identityClass', 'app\\models\\User')
#2 C:\xampp\htdocs\yii\base\CModule.php(393): YiiBase::createComponent(Array)
#3 C:\xampp\htdocs\yii\base\CModule.php(103): CModule->getComponent('user')
#4 C:\xampp\htdocs\pruebaTecnica\protected\views\layouts\main.php(35): CModule->__get('user')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#9 C:\xampp\htdocs\yii\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#10 C:\xampp\htdocs\yii\web\CBaseController.php(214): COutputProcessor->run()
#11 C:\xampp\htdocs\yii\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#12 C:\xampp\htdocs\pruebaTecnica\protected\views\layouts\column1.php(6): CBaseController->endContent()
#13 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#14 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#15 C:\xampp\htdocs\yii\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#16 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(98): CController->render('login', Array)
#17 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#18 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#19 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#20 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#21 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#22 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#23 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#24 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#25 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=site/login
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=site/index
---
2023/06/15 21:10:28 [error] [exception.CException] CException: Property "CWebUser.identityClass" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CWebUser.php(160): CComponent->__set('identityClass', 'app\\models\\User')
#1 C:\xampp\htdocs\yii\YiiBase.php(220): CWebUser->__set('identityClass', 'app\\models\\User')
#2 C:\xampp\htdocs\yii\base\CModule.php(393): YiiBase::createComponent(Array)
#3 C:\xampp\htdocs\yii\web\CWebApplication.php(209): CModule->getComponent('user')
#4 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(132): CWebApplication->getUser()
#5 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios')
#13 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=usuarios
---
2023/06/15 21:10:28 [error] [exception.CException] CException: Property "CWebUser.identityClass" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CWebUser.php(160): CComponent->__set('identityClass', 'app\\models\\User')
#1 C:\xampp\htdocs\yii\YiiBase.php(220): CWebUser->__set('identityClass', 'app\\models\\User')
#2 C:\xampp\htdocs\yii\base\CModule.php(393): YiiBase::createComponent(Array)
#3 C:\xampp\htdocs\yii\web\CWebApplication.php(209): CModule->getComponent('user')
#4 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(132): CWebApplication->getUser()
#5 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios')
#13 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=usuarios
---
2023/06/15 21:13:11 [error] [exception.CException] CException: Property "CWebUser.identityClass" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CWebUser.php(160): CComponent->__set('identityClass', 'app\\models\\User')
#1 C:\xampp\htdocs\yii\YiiBase.php(220): CWebUser->__set('identityClass', 'app\\models\\User')
#2 C:\xampp\htdocs\yii\base\CModule.php(393): YiiBase::createComponent(Array)
#3 C:\xampp\htdocs\yii\web\CWebApplication.php(209): CModule->getComponent('user')
#4 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(132): CWebApplication->getUser()
#5 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios')
#13 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=usuarios
---
2023/06/15 21:17:11 [error] [exception.CException] CException: Property "CWebUser.identityClass" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CWebUser.php(160): CComponent->__set('identityClass', 'app\\models\\User')
#1 C:\xampp\htdocs\yii\YiiBase.php(220): CWebUser->__set('identityClass', 'app\\models\\User')
#2 C:\xampp\htdocs\yii\base\CModule.php(393): YiiBase::createComponent(Array)
#3 C:\xampp\htdocs\yii\base\CModule.php(103): CModule->getComponent('user')
#4 C:\xampp\htdocs\pruebaTecnica\protected\views\layouts\main.php(35): CModule->__get('user')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#9 C:\xampp\htdocs\yii\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#10 C:\xampp\htdocs\yii\web\CBaseController.php(214): COutputProcessor->run()
#11 C:\xampp\htdocs\yii\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#12 C:\xampp\htdocs\pruebaTecnica\protected\views\layouts\column1.php(6): CBaseController->endContent()
#13 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#14 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#15 C:\xampp\htdocs\yii\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#16 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(32): CController->render('index')
#17 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#18 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#19 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#20 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#21 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#22 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#23 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#24 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#25 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=usuarios
---
2023/06/15 21:17:12 [error] [exception.CException] CException: Property "CWebUser.identityClass" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CWebUser.php(160): CComponent->__set('identityClass', 'app\\models\\User')
#1 C:\xampp\htdocs\yii\YiiBase.php(220): CWebUser->__set('identityClass', 'app\\models\\User')
#2 C:\xampp\htdocs\yii\base\CModule.php(393): YiiBase::createComponent(Array)
#3 C:\xampp\htdocs\yii\base\CModule.php(103): CModule->getComponent('user')
#4 C:\xampp\htdocs\pruebaTecnica\protected\views\layouts\main.php(35): CModule->__get('user')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#9 C:\xampp\htdocs\yii\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#10 C:\xampp\htdocs\yii\web\CBaseController.php(214): COutputProcessor->run()
#11 C:\xampp\htdocs\yii\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#12 C:\xampp\htdocs\pruebaTecnica\protected\views\layouts\column1.php(6): CBaseController->endContent()
#13 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#14 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#15 C:\xampp\htdocs\yii\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#16 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(32): CController->render('index')
#17 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#18 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#19 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#20 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#21 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#22 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#23 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#24 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#25 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=usuarios
---
2023/06/15 21:17:12 [error] [exception.CException] CException: Property "CWebUser.identityClass" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CWebUser.php(160): CComponent->__set('identityClass', 'app\\models\\User')
#1 C:\xampp\htdocs\yii\YiiBase.php(220): CWebUser->__set('identityClass', 'app\\models\\User')
#2 C:\xampp\htdocs\yii\base\CModule.php(393): YiiBase::createComponent(Array)
#3 C:\xampp\htdocs\yii\base\CModule.php(103): CModule->getComponent('user')
#4 C:\xampp\htdocs\pruebaTecnica\protected\views\layouts\main.php(35): CModule->__get('user')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#9 C:\xampp\htdocs\yii\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#10 C:\xampp\htdocs\yii\web\CBaseController.php(214): COutputProcessor->run()
#11 C:\xampp\htdocs\yii\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#12 C:\xampp\htdocs\pruebaTecnica\protected\views\layouts\column1.php(6): CBaseController->endContent()
#13 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#14 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#15 C:\xampp\htdocs\yii\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#16 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(32): CController->render('index')
#17 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#18 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#19 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#20 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#21 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#22 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#23 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#24 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#25 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=usuarios
---
2023/06/15 21:17:32 [error] [exception.CException] CException: Property "CWebUser.identityClass" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CWebUser.php(160): CComponent->__set('identityClass', 'app\\models\\Usua...')
#1 C:\xampp\htdocs\yii\YiiBase.php(220): CWebUser->__set('identityClass', 'app\\models\\Usua...')
#2 C:\xampp\htdocs\yii\base\CModule.php(393): YiiBase::createComponent(Array)
#3 C:\xampp\htdocs\yii\base\CModule.php(103): CModule->getComponent('user')
#4 C:\xampp\htdocs\pruebaTecnica\protected\views\layouts\main.php(35): CModule->__get('user')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#9 C:\xampp\htdocs\yii\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#10 C:\xampp\htdocs\yii\web\CBaseController.php(214): COutputProcessor->run()
#11 C:\xampp\htdocs\yii\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#12 C:\xampp\htdocs\pruebaTecnica\protected\views\layouts\column1.php(6): CBaseController->endContent()
#13 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#14 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#15 C:\xampp\htdocs\yii\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#16 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(32): CController->render('index')
#17 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#18 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#19 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#20 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#21 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#22 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#23 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#24 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#25 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=usuarios
---
2023/06/15 21:35:55 [error] [php] Undefined variable $dataProvider (C:\xampp\htdocs\pruebaTecnica\protected\views\site\index.php:18)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php
in C:\xampp\htdocs\pruebaTecnica\protected\views\site\index.php (18)
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/15 21:36:43 [error] [exception.CException] CException: SiteController cannot find the requested view "index". in C:\xampp\htdocs\yii\web\CController.php:878
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', NULL, true)
#1 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(32): CController->render('index')
#2 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('')
#8 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/pruebaTecnica/index.php
---
2023/06/15 21:38:30 [error] [php] Undefined variable $dataProvider (C:\xampp\htdocs\pruebaTecnica\protected\views\site\index.php:22)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php
in C:\xampp\htdocs\pruebaTecnica\protected\views\site\index.php (22)
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/15 21:38:31 [error] [php] Undefined variable $dataProvider (C:\xampp\htdocs\pruebaTecnica\protected\views\site\index.php:22)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php
in C:\xampp\htdocs\pruebaTecnica\protected\views\site\index.php (22)
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/15 21:38:32 [error] [php] Undefined variable $dataProvider (C:\xampp\htdocs\pruebaTecnica\protected\views\site\index.php:22)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php
in C:\xampp\htdocs\pruebaTecnica\protected\views\site\index.php (22)
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/15 21:47:04 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "products". in C:\xampp\htdocs\yii\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(270): CController->missingAction('products')
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('products')
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/products')
#3 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=site/products
HTTP_REFERER=http://localhost/pruebaTecnica/index.php
---
2023/06/15 21:50:06 [error] [exception.CException] CException: Property "Usuarios.rememberMe" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(145): CComponent->__get('rememberMe')
#1 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2729): CActiveRecord->__get('rememberMe')
#2 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1923): CHtml::resolveValue(Object(Usuarios), 'rememberMe')
#3 C:\xampp\htdocs\yii\web\widgets\CActiveForm.php(898): CHtml::activeCheckBox(Object(Usuarios), 'rememberMe', Array)
#4 C:\xampp\htdocs\pruebaTecnica\protected\views\site\login.php(43): CActiveForm->checkBox(Object(Usuarios), 'rememberMe')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(93): CController->render('login', Array)
#10 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionProducts()
#11 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('products')
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/products')
#16 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=site/products
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=site/index
---
2023/06/15 22:44:21 [error] [exception.CException] CException: Property "Usuarios.rememberMe" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(145): CComponent->__get('rememberMe')
#1 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2729): CActiveRecord->__get('rememberMe')
#2 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1923): CHtml::resolveValue(Object(Usuarios), 'rememberMe')
#3 C:\xampp\htdocs\yii\web\widgets\CActiveForm.php(898): CHtml::activeCheckBox(Object(Usuarios), 'rememberMe', Array)
#4 C:\xampp\htdocs\pruebaTecnica\protected\views\site\login.php(43): CActiveForm->checkBox(Object(Usuarios), 'rememberMe')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(93): CController->render('login', Array)
#10 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionProducts()
#11 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('products')
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/products')
#16 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=site/products
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=site/index
---
2023/06/15 22:45:00 [error] [exception.CException] CException: Property "Usuarios.rememberMe" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(145): CComponent->__get('rememberMe')
#1 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2729): CActiveRecord->__get('rememberMe')
#2 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1923): CHtml::resolveValue(Object(Usuarios), 'rememberMe')
#3 C:\xampp\htdocs\yii\web\widgets\CActiveForm.php(898): CHtml::activeCheckBox(Object(Usuarios), 'rememberMe', Array)
#4 C:\xampp\htdocs\pruebaTecnica\protected\views\site\login.php(43): CActiveForm->checkBox(Object(Usuarios), 'rememberMe')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(93): CController->render('login', Array)
#10 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionProducts()
#11 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('products')
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/products')
#16 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=site/products
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=usuarios
---
2023/06/15 22:45:06 [error] [exception.CException] CException: Property "Usuarios.rememberMe" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(145): CComponent->__get('rememberMe')
#1 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2729): CActiveRecord->__get('rememberMe')
#2 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1923): CHtml::resolveValue(Object(Usuarios), 'rememberMe')
#3 C:\xampp\htdocs\yii\web\widgets\CActiveForm.php(898): CHtml::activeCheckBox(Object(Usuarios), 'rememberMe', Array)
#4 C:\xampp\htdocs\pruebaTecnica\protected\views\site\login.php(43): CActiveForm->checkBox(Object(Usuarios), 'rememberMe')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(93): CController->render('login', Array)
#10 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionProducts()
#11 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('products')
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/products')
#16 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=site/products
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=usuarios
---
2023/06/15 23:08:47 [error] [php] include(Article.php): Failed to open stream: No such file or directory (C:\xampp\htdocs\yii\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#1 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#2 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): ProductController->runAction()
#3 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#5 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): ProductController->filterAccessControl()
#6 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#7 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\yii\web\CController.php(265): ProductController->runActionWithFilters()
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(282): ProductController->run()
#10 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#11 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#12 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php?r=product
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php (150)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/15 23:13:59 [error] [php] Undefined variable $dataProvider (C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php:18)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(869): ProductController->renderFile()
#1 C:\xampp\htdocs\yii\web\CController.php(782): ProductController->renderPartial()
#2 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(154): ProductController->render()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): ProductController->runAction()
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): ProductController->filterAccessControl()
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): ProductController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): ProductController->run()
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php?r=product
in C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php (18)
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php (154)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/16 00:00:49 [error] [exception.Error] Error: Object of class Productos could not be converted to string in C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php:22
Stack trace:
#0 C:\xampp\htdocs\yii\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#2 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#3 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#4 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(154): CController->render('index', Array)
#5 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#6 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#9 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('index')
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/index')
#16 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product/index
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=product/index&page=2
---
2023/06/16 00:04:42 [error] [exception.CException] CException: Property "Productos.marca" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(145): CComponent->__get('marca')
#1 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2729): CActiveRecord->__get('marca')
#2 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1834): CHtml::resolveValue(Object(Productos), 'marca')
#3 C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php(42): CHtml::activeTextArea(Object(Productos), 'marca')
#4 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#8 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(154): CController->render('index', Array)
#9 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#10 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/index')
#20 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product/index
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=product/index&page=2
---
2023/06/16 00:16:39 [error] [exception.CException] CException: Property "Productos.1" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(145): CComponent->__get('1')
#1 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2729): CActiveRecord->__get('1')
#2 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1923): CHtml::resolveValue(Object(Productos), '1')
#3 C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php(44): CHtml::activeCheckBox(Object(Productos), '1')
#4 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#8 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(154): CController->render('index', Array)
#9 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#10 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product')
#20 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=usuarios
---
2023/06/16 00:31:55 [error] [exception.CException] CException: Property "Productos.1" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(145): CComponent->__get('1')
#1 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2729): CActiveRecord->__get('1')
#2 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1923): CHtml::resolveValue(Object(Productos), '1')
#3 C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php(44): CHtml::activeCheckBox(Object(Productos), '1')
#4 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#8 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(154): CController->render('index', Array)
#9 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#10 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product')
#20 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=usuarios
---
2023/06/16 00:32:58 [error] [exception.CException] CException: Property "Productos.marca" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(145): CComponent->__get('marca')
#1 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2729): CActiveRecord->__get('marca')
#2 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1923): CHtml::resolveValue(Object(Productos), 'marca')
#3 C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php(44): CHtml::activeCheckBox(Object(Productos), 'marca')
#4 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#8 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(154): CController->render('index', Array)
#9 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#10 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product')
#20 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=usuarios
---
2023/06/16 00:57:28 [error] [exception.Error] Error: Call to a member function with() on array in C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php:155
Stack trace:
#0 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#1 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#3 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#10 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product')
#11 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#12 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=site/index
---
2023/06/16 00:58:29 [error] [exception.Error] Error: Call to a member function with() on array in C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php:155
Stack trace:
#0 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#1 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#3 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#4 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#8 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#10 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product')
#11 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#12 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=site/index
---
2023/06/16 01:11:27 [error] [php] Object of class Marcas could not be converted to int (C:\xampp\htdocs\yii\web\helpers\CHtml.php:1923)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CBaseController.php(95): ProductController->renderInternal()
#1 C:\xampp\htdocs\yii\web\CController.php(869): ProductController->renderFile()
#2 C:\xampp\htdocs\yii\web\CController.php(782): ProductController->renderPartial()
#3 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(155): ProductController->render()
#4 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#5 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): ProductController->runAction()
#7 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#8 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#9 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): ProductController->filterAccessControl()
#10 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#11 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#12 C:\xampp\htdocs\yii\web\CController.php(265): ProductController->runActionWithFilters()
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(282): ProductController->run()
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#15 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#16 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php?r=product
in C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php (44)
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php (155)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/16 01:20:47 [error] [exception.Error] Error: Object of class Marcas could not be converted to string in C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php:44
Stack trace:
#0 C:\xampp\htdocs\yii\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#2 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#3 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#4 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(155): CController->render('index', Array)
#5 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#6 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#9 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product')
#16 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=site/index
---
2023/06/16 01:21:16 [error] [exception.CException] CException: Property "Productos.marca->marca" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(145): CComponent->__get('marca->marca')
#1 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2729): CActiveRecord->__get('marca->marca')
#2 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Productos), 'marca->marca')
#3 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(Productos), 'marca->marca', Array)
#4 C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php(44): CHtml::activeTextField(Object(Productos), 'marca->marca')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#9 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(155): CController->render('index', Array)
#10 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#11 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#14 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#17 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#18 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#19 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#20 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product')
#21 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#22 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#23 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=site/index
---
2023/06/16 02:22:41 [error] [exception.TypeError] TypeError: Cannot access offset of type string on string in C:\xampp\htdocs\yii\web\helpers\CHtml.php:2658
Stack trace:
#0 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1532): CHtml::resolveNameID(Object(Productos), 'codigo', 'readOnly')
#1 C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php(35): CHtml::activeTextField(Object(Productos), 'codigo', 'readOnly')
#2 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#6 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(155): CController->render('index', Array)
#7 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#8 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#15 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product')
#18 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#19 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=site/index
---
2023/06/16 02:23:12 [error] [exception.TypeError] TypeError: Cannot access offset of type string on string in C:\xampp\htdocs\yii\web\helpers\CHtml.php:2658
Stack trace:
#0 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1532): CHtml::resolveNameID(Object(Productos), 'codigo', 'readOnly')
#1 C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php(35): CHtml::activeTextField(Object(Productos), 'codigo', 'readOnly')
#2 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#6 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(155): CController->render('index', Array)
#7 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#8 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#15 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product')
#18 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#19 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=site/index
---
2023/06/16 02:24:37 [error] [exception.TypeError] TypeError: htmlspecialchars(): Argument #1 ($string) must be of type string, array given in C:\xampp\htdocs\yii\web\helpers\CHtml.php:108
Stack trace:
#0 C:\xampp\htdocs\yii\web\helpers\CHtml.php(108): htmlspecialchars(Array, 3, 'UTF-8')
#1 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2814): CHtml::encode(Array)
#2 C:\xampp\htdocs\yii\web\helpers\CHtml.php(163): CHtml::renderAttributes(Array)
#3 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2455): CHtml::tag('input', Array)
#4 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(Productos), 'codigo', Array)
#5 C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php(35): CHtml::activeTextField(Object(Productos), 'codigo', Array)
#6 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(155): CController->render('index', Array)
#11 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#12 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#21 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product')
#22 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=site/index
---
2023/06/16 02:24:46 [error] [exception.CException] CException: Property "Productos.checked" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(145): CComponent->__get('checked')
#1 C:\xampp\htdocs\yii\web\helpers\CHtml.php(2729): CActiveRecord->__get('checked')
#2 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1923): CHtml::resolveValue(Object(Productos), 'checked')
#3 C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php(44): CHtml::activeCheckBox(Object(Productos), 'checked')
#4 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#8 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(155): CController->render('index', Array)
#9 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#10 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product')
#20 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=site/index
---
2023/06/16 02:26:08 [error] [exception.TypeError] TypeError: Cannot access offset of type string on string in C:\xampp\htdocs\yii\web\helpers\CHtml.php:2658
Stack trace:
#0 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1920): CHtml::resolveNameID(Object(Productos), 'nombre', 'checked')
#1 C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php(44): CHtml::activeCheckBox(Object(Productos), 'nombre', 'checked')
#2 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#6 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(155): CController->render('index', Array)
#7 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#8 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#15 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product')
#18 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#19 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=site/index
---
2023/06/16 02:28:14 [error] [exception.CException] CException: Property "Productos.clave" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(145): CComponent->__get('clave')
#1 C:\xampp\htdocs\yii\base\CModel.php(596): CActiveRecord->__get('clave')
#2 C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php(35): CModel->offsetGet('clave')
#3 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#7 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(155): CController->render('index', Array)
#8 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#9 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=site/index
---
2023/06/16 02:35:53 [error] [php] Object of class Marcas could not be converted to int (C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php:34)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(869): ProductController->renderFile()
#1 C:\xampp\htdocs\yii\web\CController.php(782): ProductController->renderPartial()
#2 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(155): ProductController->render()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): ProductController->runAction()
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): ProductController->filterAccessControl()
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): ProductController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): ProductController->run()
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php?r=product/index
in C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php (34)
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php (155)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/16 06:46:32 [error] [php] Attempt to read property "city" on int (C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php:67)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(869): ProductController->renderFile()
#1 C:\xampp\htdocs\yii\web\CController.php(782): ProductController->renderPartial()
#2 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(152): ProductController->render()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): ProductController->runAction()
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): ProductController->filterAccessControl()
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): ProductController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): ProductController->run()
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php?r=product
in C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php (67)
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php (152)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/16 06:47:11 [error] [exception.CException] CException: Property "Productos.name" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(145): CComponent->__get('name')
#1 C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php(69): CActiveRecord->__get('name')
#2 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#6 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(152): CController->render('index', Array)
#7 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#8 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#15 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product')
#18 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#19 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product
HTTP_REFERER=http://localhost/pruebaTecnica/index.php
---
2023/06/16 06:56:03 [error] [php] include(Url.php): Failed to open stream: No such file or directory (C:\xampp\htdocs\yii\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\yii\web\CBaseController.php(95): ProductController->renderInternal()
#2 C:\xampp\htdocs\yii\web\CController.php(869): ProductController->renderFile()
#3 C:\xampp\htdocs\yii\web\CController.php(782): ProductController->renderPartial()
#4 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(152): ProductController->render()
#5 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#6 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#7 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): ProductController->runAction()
#8 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#9 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#10 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): ProductController->filterAccessControl()
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#12 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(265): ProductController->runActionWithFilters()
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(282): ProductController->run()
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#16 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php?r=product/index
in C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php (50)
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php (152)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/16 06:56:33 [error] [exception.Error] Error: Class "yii\helpers\Url" not found in C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php:52
Stack trace:
#0 C:\xampp\htdocs\yii\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#2 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#3 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#4 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(152): CController->render('index', Array)
#5 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#6 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#9 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('index')
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/index')
#16 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product/index
HTTP_REFERER=http://localhost/pruebaTecnica/index.php?r=product/index&page=2
---
2023/06/16 06:59:23 [error] [php] include(Url.php): Failed to open stream: No such file or directory (C:\xampp\htdocs\yii\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\yii\web\CBaseController.php(95): ProductController->renderInternal()
#2 C:\xampp\htdocs\yii\web\CController.php(869): ProductController->renderFile()
#3 C:\xampp\htdocs\yii\web\CController.php(782): ProductController->renderPartial()
#4 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(152): ProductController->render()
#5 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#6 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#7 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): ProductController->runAction()
#8 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#9 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#10 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): ProductController->filterAccessControl()
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#12 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(265): ProductController->runActionWithFilters()
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(282): ProductController->run()
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#16 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php/product
in C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php (50)
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php (152)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/16 07:04:12 [error] [php] include(Url.php): Failed to open stream: No such file or directory (C:\xampp\htdocs\yii\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\yii\web\CBaseController.php(95): ProductController->renderInternal()
#2 C:\xampp\htdocs\yii\web\CController.php(869): ProductController->renderFile()
#3 C:\xampp\htdocs\yii\web\CController.php(782): ProductController->renderPartial()
#4 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(152): ProductController->render()
#5 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#6 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#7 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): ProductController->runAction()
#8 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#9 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#10 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): ProductController->filterAccessControl()
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#12 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(265): ProductController->runActionWithFilters()
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(282): ProductController->run()
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#16 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php?r=product/index
in C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php (50)
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php (152)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/16 07:04:19 [error] [exception.CException] CException: Alias "Prueba.models.*" is invalid. Make sure it points to an existing directory or file. in C:\xampp\htdocs\yii\YiiBase.php:348
Stack trace:
#0 C:\xampp\htdocs\yii\base\CModule.php(226): YiiBase::import('Prueba.models.*')
#1 C:\xampp\htdocs\pruebaTecnica\protected\modules\Prueba\PruebaModule.php(11): CModule->setImport(Array)
#2 C:\xampp\htdocs\yii\base\CModule.php(90): PruebaModule->init()
#3 C:\xampp\htdocs\yii\YiiBase.php(206): CModule->__construct('prueba', NULL, Array)
#4 C:\xampp\htdocs\yii\base\CModule.php(282): YiiBase::createComponent(Array, 'prueba', NULL, Array)
#5 C:\xampp\htdocs\yii\web\CWebApplication.php(337): CModule->getModule('prueba')
#6 C:\xampp\htdocs\yii\web\CWebApplication.php(276): CWebApplication->createController('')
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('prueba')
#8 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=prueba
---
2023/06/16 07:04:30 [error] [exception.CException] CException: Alias "Prueba.models.*" is invalid. Make sure it points to an existing directory or file. in C:\xampp\htdocs\yii\YiiBase.php:348
Stack trace:
#0 C:\xampp\htdocs\yii\base\CModule.php(226): YiiBase::import('Prueba.models.*')
#1 C:\xampp\htdocs\pruebaTecnica\protected\modules\Prueba\PruebaModule.php(11): CModule->setImport(Array)
#2 C:\xampp\htdocs\yii\base\CModule.php(90): PruebaModule->init()
#3 C:\xampp\htdocs\yii\YiiBase.php(206): CModule->__construct('prueba', NULL, Array)
#4 C:\xampp\htdocs\yii\base\CModule.php(282): YiiBase::createComponent(Array, 'prueba', NULL, Array)
#5 C:\xampp\htdocs\yii\web\CWebApplication.php(337): CModule->getModule('prueba')
#6 C:\xampp\htdocs\yii\web\CWebApplication.php(276): CWebApplication->createController('')
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('prueba')
#8 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=prueba
---
2023/06/16 07:04:51 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "prueba". in C:\xampp\htdocs\yii\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('prueba')
#1 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=prueba
---
2023/06/16 07:06:27 [error] [exception.Error] Error: Class "yii\helpers\Url" not found in C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php:52
Stack trace:
#0 C:\xampp\htdocs\yii\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#2 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#3 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#4 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(152): CController->render('index', Array)
#5 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#6 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#9 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product')
#16 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/pruebaTecnica/index.php?r=product
HTTP_REFERER=http://localhost/pruebaTecnica/index.php
---
2023/06/16 07:15:28 [error] [php] include(User.php): Failed to open stream: No such file or directory (C:\xampp\htdocs\yii\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\pruebaTecnica\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#1 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate()
#2 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#3 C:\xampp\htdocs\yii\base\CModel.php(159): CInlineValidator->validate()
#4 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(110): LoginForm->validate()
#5 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#6 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#7 C:\xampp\htdocs\yii\web\CController.php(286): SiteController->runAction()
#8 C:\xampp\htdocs\yii\web\CController.php(265): SiteController->runActionWithFilters()
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(282): SiteController->run()
#10 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#11 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#12 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php?r=site/login
in C:\xampp\htdocs\pruebaTecnica\protected\components\UserIdentity.php (23)
in C:\xampp\htdocs\pruebaTecnica\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php (110)
2023/06/16 07:31:33 [error] [exception.Error] Error: Cannot unset offset in a non-array variable in C:\xampp\htdocs\yii\web\CUrlManager.php:285
Stack trace:
#0 C:\xampp\htdocs\yii\base\CApplication.php(561): CUrlManager->createUrl('product/create', 1, '&')
#1 C:\xampp\htdocs\yii\web\CController.php(967): CApplication->createUrl('product/create', 1, '&')
#2 C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php(50): CController->createUrl('product/create', 1)
#3 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#7 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(152): CController->render('index', Array)
#8 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#9 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('')
#18 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product')
#19 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/pruebaTecnica/index.php/product
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios
---
2023/06/16 07:53:48 [error] [php] include(User.php): Failed to open stream: No such file or directory (C:\xampp\htdocs\yii\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\pruebaTecnica\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#1 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate()
#2 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#3 C:\xampp\htdocs\yii\base\CModel.php(159): CInlineValidator->validate()
#4 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(110): LoginForm->validate()
#5 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#6 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#7 C:\xampp\htdocs\yii\web\CController.php(286): SiteController->runAction()
#8 C:\xampp\htdocs\yii\web\CController.php(265): SiteController->runActionWithFilters()
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(282): SiteController->run()
#10 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#11 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#12 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php/site/login
in C:\xampp\htdocs\pruebaTecnica\protected\components\UserIdentity.php (23)
in C:\xampp\htdocs\pruebaTecnica\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php (110)
2023/06/16 08:00:46 [error] [exception.CException] CException: Usuarios and its behaviors do not have a method or closure named "validatePassword". in C:\xampp\htdocs\yii\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(227): CComponent->__call('validatePasswor...', Array)
#1 C:\xampp\htdocs\pruebaTecnica\protected\components\UserIdentity.php(26): CActiveRecord->__call('validatePasswor...', Array)
#2 C:\xampp\htdocs\pruebaTecnica\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#6 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(110): CModel->validate()
#7 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/pruebaTecnica/index.php/site/login
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/site/login
---
2023/06/16 08:14:06 [error] [exception.CException] CException: Usuarios and its behaviors do not have a method or closure named "validatePassword". in C:\xampp\htdocs\yii\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(227): CComponent->__call('validatePasswor...', Array)
#1 C:\xampp\htdocs\pruebaTecnica\protected\components\UserIdentity.php(26): CActiveRecord->__call('validatePasswor...', Array)
#2 C:\xampp\htdocs\pruebaTecnica\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#6 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(110): CModel->validate()
#7 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/pruebaTecnica/index.php/site/login
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/site/login
---
2023/06/16 08:19:31 [error] [exception.CException] CException: Property "Usuarios.salt" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(145): CComponent->__get('salt')
#1 C:\xampp\htdocs\pruebaTecnica\protected\models\Usuarios.php(47): CActiveRecord->__get('salt')
#2 C:\xampp\htdocs\pruebaTecnica\protected\components\UserIdentity.php(26): Usuarios->validatePassword('12345')
#3 C:\xampp\htdocs\pruebaTecnica\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#4 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#7 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(110): CModel->validate()
#8 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#9 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/pruebaTecnica/index.php/site/login
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/site/login
---
2023/06/16 08:59:24 [error] [php] Undefined array key "LoginForm" (C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php:99)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(286): SiteController->runAction()
#1 C:\xampp\htdocs\yii\web\CController.php(265): SiteController->runActionWithFilters()
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(282): SiteController->run()
#3 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php/site/login
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php (99)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/16 09:17:51 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens. The SQL statement executed was: SELECT * FROM `usuarios` `t` WHERE username LIMIT 1.
in C:\xampp\htdocs\pruebaTecnica\protected\components\UserIdentity.php (23)
in C:\xampp\htdocs\pruebaTecnica\protected\models\LoginForm.php (51)
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php (110)
2023/06/16 09:17:51 [error] [exception.CDbException] CDbException: CDbCommand failed to execute the SQL statement: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens. The SQL statement executed was: SELECT * FROM `usuarios` `t` WHERE username LIMIT 1 in C:\xampp\htdocs\yii\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii\db\CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1356): CDbCommand->queryRow()
#2 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(1461): CActiveRecord->query(Object(CDbCriteria))
#3 C:\xampp\htdocs\pruebaTecnica\protected\components\UserIdentity.php(23): CActiveRecord->find('username', Array)
#4 C:\xampp\htdocs\pruebaTecnica\protected\models\LoginForm.php(51): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#8 C:\xampp\htdocs\pruebaTecnica\protected\controllers\SiteController.php(110): CModel->validate()
#9 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('login')
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#16 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/pruebaTecnica/index.php/site/login
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/site/login
---
2023/06/16 09:31:23 [error] [php] Attempt to read property "password" on array (C:\xampp\htdocs\pruebaTecnica\protected\controllers\UsuariosController.php:84)
Stack trace:
#0 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): UsuariosController->runAction()
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): UsuariosController->filterAccessControl()
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): UsuariosController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): UsuariosController->run()
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php/usuarios/create
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\UsuariosController.php (84)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/16 09:34:55 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/view')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/view?0=index
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/create
---
2023/06/16 09:35:25 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/view')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/view?0=index
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/create
---
2023/06/16 09:35:56 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "usuarios". in C:\xampp\htdocs\yii\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/usuari...')
#3 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/usuarios/index
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/create
---
2023/06/16 09:36:13 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/view')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/view?0=usuarios%2Findex
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/create
---
2023/06/16 09:37:43 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/view')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/view?index=usuarios%2Findex
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/create
---
2023/06/16 09:50:50 [error] [exception.TypeError] TypeError: mb_strlen(): Argument #1 ($string) must be of type string, Marcas given in C:\xampp\htdocs\yii\validators\CStringValidator.php:91
Stack trace:
#0 C:\xampp\htdocs\yii\validators\CStringValidator.php(91): mb_strlen(Object(Marcas), 'UTF-8')
#1 C:\xampp\htdocs\yii\validators\CValidator.php(201): CStringValidator->validateAttribute(Object(Productos), 'marca')
#2 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(Productos), Array)
#3 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(808): CModel->validate(NULL)
#4 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(110): CActiveRecord->save()
#5 [internal function]: ProductController->actionUpdate('1')
#6 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(ProductController), Array)
#7 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ProductController), Object(ReflectionMethod), Array)
#8 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#15 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('update')
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/update')
#18 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#19 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/pruebaTecnica/index.php/product/update/1
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/product/update/1
---
2023/06/16 09:52:23 [error] [exception.TypeError] TypeError: mb_strlen(): Argument #1 ($string) must be of type string, Marcas given in C:\xampp\htdocs\yii\validators\CStringValidator.php:91
Stack trace:
#0 C:\xampp\htdocs\yii\validators\CStringValidator.php(91): mb_strlen(Object(Marcas), 'UTF-8')
#1 C:\xampp\htdocs\yii\validators\CValidator.php(201): CStringValidator->validateAttribute(Object(Productos), 'marca')
#2 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(Productos), Array)
#3 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(808): CModel->validate(NULL)
#4 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(84): CActiveRecord->save()
#5 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionCreate()
#6 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#9 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#11 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#13 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#15 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/create')
#16 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/pruebaTecnica/index.php/product/create
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/product/create
---
2023/06/16 09:56:09 [error] [exception.TypeError] TypeError: mb_strlen(): Argument #1 ($string) must be of type string, Marcas given in C:\xampp\htdocs\yii\validators\CStringValidator.php:91
Stack trace:
#0 C:\xampp\htdocs\yii\validators\CStringValidator.php(91): mb_strlen(Object(Marcas), 'UTF-8')
#1 C:\xampp\htdocs\yii\validators\CValidator.php(201): CStringValidator->validateAttribute(Object(Productos), 'marca')
#2 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(Productos), Array)
#3 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(808): CModel->validate(NULL)
#4 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(110): CActiveRecord->save()
#5 [internal function]: ProductController->actionUpdate('1')
#6 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(ProductController), Array)
#7 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ProductController), Object(ReflectionMethod), Array)
#8 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#15 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('update')
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/update')
#18 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#19 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/pruebaTecnica/index.php/product/update/1
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/product/update/1
---
2023/06/16 09:58:05 [error] [exception.TypeError] TypeError: mb_strlen(): Argument #1 ($string) must be of type string, Marcas given in C:\xampp\htdocs\yii\validators\CStringValidator.php:91
Stack trace:
#0 C:\xampp\htdocs\yii\validators\CStringValidator.php(91): mb_strlen(Object(Marcas), 'UTF-8')
#1 C:\xampp\htdocs\yii\validators\CValidator.php(201): CStringValidator->validateAttribute(Object(Productos), 'marca')
#2 C:\xampp\htdocs\yii\base\CModel.php(159): CValidator->validate(Object(Productos), Array)
#3 C:\xampp\htdocs\yii\db\ar\CActiveRecord.php(808): CModel->validate(NULL)
#4 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(110): CActiveRecord->save()
#5 [internal function]: ProductController->actionUpdate('1')
#6 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(ProductController), Array)
#7 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ProductController), Object(ReflectionMethod), Array)
#8 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#15 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('update')
#17 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/update')
#18 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#19 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/pruebaTecnica/index.php/product/update/1
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/product/update/1
---
2023/06/16 10:02:18 [error] [exception.CHttpException.403] CHttpException: You are not authorized to perform this action. in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/delete')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pruebaTecnica/index.php/product/delete/8
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/product/index?page=2
---
2023/06/16 10:03:04 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:1118
Stack trace:
#0 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/delete')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/product/delete/8
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/product/index?page=2
---
2023/06/16 10:03:54 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:1118
Stack trace:
#0 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/delete')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/product/delete/8
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/product/index?page=2
---
2023/06/16 10:04:30 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:1118
Stack trace:
#0 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/delete')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/product/delete/8
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/product/index?page=2
---
2023/06/16 10:06:06 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:1118
Stack trace:
#0 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/delete')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/product/delete/5
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/product/index
---
2023/06/16 10:08:53 [error] [exception.CHttpException.403] CHttpException: You are not authorized to perform this action. in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/delete')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/delete/26
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/26
---
2023/06/16 10:09:39 [error] [exception.CHttpException.403] CHttpException: You are not authorized to perform this action. in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/admin')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/admin
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/26
---
2023/06/16 10:09:42 [error] [exception.CHttpException.404] CHttpException: The requested page does not exist. in C:\xampp\htdocs\pruebaTecnica\protected\controllers\UsuariosController.php:180
Stack trace:
#0 C:\xampp\htdocs\pruebaTecnica\protected\controllers\UsuariosController.php(66): UsuariosController->loadModel('26')
#1 [internal function]: UsuariosController->actionView('26')
#2 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsuariosController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/view')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/26
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/index
---
2023/06/16 10:09:44 [error] [exception.CHttpException.404] CHttpException: The requested page does not exist. in C:\xampp\htdocs\pruebaTecnica\protected\controllers\UsuariosController.php:180
Stack trace:
#0 C:\xampp\htdocs\pruebaTecnica\protected\controllers\UsuariosController.php(66): UsuariosController->loadModel('26')
#1 [internal function]: UsuariosController->actionView('26')
#2 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsuariosController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/view')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/26
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/index
---
2023/06/16 10:09:45 [error] [exception.CHttpException.404] CHttpException: The requested page does not exist. in C:\xampp\htdocs\pruebaTecnica\protected\controllers\UsuariosController.php:180
Stack trace:
#0 C:\xampp\htdocs\pruebaTecnica\protected\controllers\UsuariosController.php(66): UsuariosController->loadModel('26')
#1 [internal function]: UsuariosController->actionView('26')
#2 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsuariosController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/view')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/26
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/index
---
2023/06/16 10:12:30 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/view')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/view?index=index
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/27
---
2023/06/16 10:12:53 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/view')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/view?0=index
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/27
---
2023/06/16 10:13:23 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:1118
Stack trace:
#0 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/delete...')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/delete/index
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/27
---
2023/06/16 10:13:44 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:1118
Stack trace:
#0 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/delete...')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/delete/usuarios/index
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/27
---
2023/06/16 10:14:31 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:1118
Stack trace:
#0 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/delete')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/delete
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/27
---
2023/06/16 10:14:45 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:1118
Stack trace:
#0 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/delete')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/delete
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/27
---
2023/06/16 10:15:06 [error] [exception.CHttpException.403] CHttpException: You are not authorized to perform this action. in C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/admin')
#9 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/admin
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/27
---
2023/06/16 10:19:23 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:1118
Stack trace:
#0 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/delete')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/delete
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/27
---
2023/06/16 10:19:43 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:1118
Stack trace:
#0 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/delete')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/delete
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/27
---
2023/06/16 10:19:49 [error] [exception.CHttpException.404] CHttpException: The requested page does not exist. in C:\xampp\htdocs\pruebaTecnica\protected\controllers\UsuariosController.php:180
Stack trace:
#0 C:\xampp\htdocs\pruebaTecnica\protected\controllers\UsuariosController.php(66): UsuariosController->loadModel('27')
#1 [internal function]: UsuariosController->actionView('27')
#2 C:\xampp\htdocs\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsuariosController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('usuarios/view')
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/pruebaTecnica/index.php/usuarios/27
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/usuarios/index
---
2023/06/16 10:26:48 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:1118
Stack trace:
#0 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/delete')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/product/delete/9
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/product/index?page=2
---
2023/06/16 10:29:54 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:1118
Stack trace:
#0 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/delete')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/product/delete/9
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/product/index?page=2
---
2023/06/16 10:30:31 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "product". in C:\xampp\htdocs\yii\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(270): CController->missingAction('product')
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('product')
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/product')
#3 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pruebaTecnica/index.php/product/product/5
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/product/index
---
2023/06/16 10:31:13 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "product". in C:\xampp\htdocs\yii\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(270): CController->missingAction('product')
#1 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('product')
#2 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/product')
#3 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pruebaTecnica/index.php/product/product/5
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/product/index
---
2023/06/16 10:31:24 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:1118
Stack trace:
#0 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/delete')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/product/delete/5
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/product/index
---
2023/06/16 10:31:36 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in C:\xampp\htdocs\yii\web\CController.php:1118
Stack trace:
#0 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#1 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('delete')
#9 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/delete')
#10 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/pruebaTecnica/index.php/product/delete/5
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/product/index
---
2023/06/16 10:36:14 [error] [php] Attempt to read property "id_marca" on null (C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php:29)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(869): ProductController->renderFile()
#1 C:\xampp\htdocs\yii\web\CController.php(782): ProductController->renderPartial()
#2 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(151): ProductController->render()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): ProductController->runAction()
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): ProductController->filterAccessControl()
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): ProductController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): ProductController->run()
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php/product/index?page=2
in C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php (29)
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php (151)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/16 10:36:22 [error] [php] Attempt to read property "id_marca" on null (C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php:29)
Stack trace:
#0 C:\xampp\htdocs\yii\web\CController.php(869): ProductController->renderFile()
#1 C:\xampp\htdocs\yii\web\CController.php(782): ProductController->renderPartial()
#2 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(151): ProductController->render()
#3 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionIndex()
#4 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): ProductController->runAction()
#6 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): ProductController->filterAccessControl()
#9 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\web\CController.php(265): ProductController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\web\CWebApplication.php(282): ProductController->run()
#13 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\pruebaTecnica\index.php(13): CWebApplication->run()
REQUEST_URI=/pruebaTecnica/index.php/product/index?page=2
in C:\xampp\htdocs\pruebaTecnica\protected\views\product\index.php (29)
in C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php (151)
in C:\xampp\htdocs\pruebaTecnica\index.php (13)
2023/06/16 10:39:18 [error] [exception.CException] CException: Property "CNumberValidator.0" is not defined. in C:\xampp\htdocs\yii\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\validators\CValidator.php(177): CComponent->__set('0', 'required')
#1 C:\xampp\htdocs\yii\base\CModel.php(287): CValidator::createValidator(0, Object(Productos), Array, Array)
#2 C:\xampp\htdocs\yii\base\CModel.php(260): CModel->createValidators()
#3 C:\xampp\htdocs\yii\base\CModel.php(304): CModel->getValidators('codigo')
#4 C:\xampp\htdocs\yii\web\helpers\CHtml.php(1514): CModel->isAttributeRequired('codigo')
#5 C:\xampp\htdocs\yii\web\widgets\CActiveForm.php(600): CHtml::activeLabelEx(Object(Productos), 'codigo', Array)
#6 C:\xampp\htdocs\pruebaTecnica\protected\views\product\_form.php(24): CActiveForm->labelEx(Object(Productos), 'codigo')
#7 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#10 C:\xampp\htdocs\pruebaTecnica\protected\views\product\create.php(18): CController->renderPartial('_form', Array)
#11 C:\xampp\htdocs\yii\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#12 C:\xampp\htdocs\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\yii\web\CController.php(782): CController->renderPartial('create', Array, true)
#15 C:\xampp\htdocs\pruebaTecnica\protected\controllers\ProductController.php(88): CController->render('create', Array)
#16 C:\xampp\htdocs\yii\web\actions\CInlineAction.php(49): ProductController->actionCreate()
#17 C:\xampp\htdocs\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\yii\web\filters\CFilter.php(40): CFilterChain->run()
#20 C:\xampp\htdocs\yii\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#21 C:\xampp\htdocs\yii\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 C:\xampp\htdocs\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#23 C:\xampp\htdocs\yii\web\CController.php(291): CFilterChain->run()
#24 C:\xampp\htdocs\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 C:\xampp\htdocs\yii\web\CWebApplication.php(282): CController->run('create')
#26 C:\xampp\htdocs\yii\web\CWebApplication.php(141): CWebApplication->runController('product/create')
#27 C:\xampp\htdocs\yii\base\CApplication.php(185): CWebApplication->processRequest()
#28 C:\xampp\htdocs\pruebaTecnica\index.php(13): CApplication->run()
#29 {main}
REQUEST_URI=/pruebaTecnica/index.php/product/create
HTTP_REFERER=http://localhost/pruebaTecnica/index.php/product/index?page=2
---
